<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Project-Planner</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <link rel="stylesheet" href="/vendor/heinrichschiller/normalize.css/normalize.css">
        <link rel="stylesheet" href="/public/assets/css/grid.css">
        <link rel="stylesheet" href="/public/assets/css/style.css">
    </head>
    <body>
        <div class="container">
            <header>
                <a href="/../dashboard/index">Project-Planner</a>
                <a href="/../dashboard/index">Dashboard</a>
                <a href="/../contacts/index">Kontakte</a>
                <a href="/../projects/index">Projekte</a>
                <a href="/../task/index">Aufgaben</a>
                <a href="/../documents/index">Dokumente</a>
                <a href="/../notes/index">Notizen</a>
                <a href="/../users/index">Benutzer</a>
            </header>
            <aside class="box-left">box-left</aside>
            <div class="box-content">
                <?php require $template; ?>
            </div>
            <div class="box-right">box-right</div>
            <footer>
                <p>&copy; Heinrich Schiller 2018-2019</p>
            </footer>
        </div>
    </body>
</html>
