<div>
    <h1>Aufgabe erstellen</h1>
</div>
<div>
    <form action="">
        <div>
            <label for="title">Titel:</label>
            <input type="text" name="title" id="title">
        </div>
        <div>
            <label for="contact">Kontakt:</label>
            <input type="text" name="contact" id="contact">
        </div>
        <div>
            <label for="project">Projekt:</label>
            <input type="text" name="contact" id="project">
        </div>
    </form>
</div>