<div>
    <h1>Aufgaben</h1>
</div>
<div>
    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Titel</th>
                <th>Anfang</th>
                <th>Ende</th>
                <th>Priorität</th>
                <th>Status</th>
                <th>Contact</th>
                <th>Projekt</th>
                <th>Getestet</th>
                <th>Verteilt</th>
                <th>Ertellt</th>
                <th>Aktualisiert</th>
            </tr>
        </thead>
        <tbody>

        <?php foreach($tasks->get() as $task): ?>
            <tr>
                <td><?= $task->getId() ?></td>
                <td><?= $task->getTitle() ?></td>
                <td><?= $task->getBegin()?></td>
                <td><?= $task->getEnd() ?></td>
                <td><?= $task->getProjectTitle() ?></td>
            </tr>
        <?php endforeach; ?>    
        </tbody>
    </table>
</div>
