<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Project-Planner</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">

        <link rel="stylesheet" href="/public/assets/css/grid.css">
    </head>
    <body>
        <div class="container">
            <header>
                <a href="/../dashboard/index">Dashboard</a>
                <a href="/../contact/index">Kontakte</a>
                <a href="/../project/index">Projekte</a>
                <a href="/../task/index">Aufgaben</a>
                <a href="/../notes/index">Notizen</a>
                <a href="/../user/index">Benutzer</a>
            </header>
            <aside class="box-left">box-left</aside>
            <div class="box-content">
                <?php require $template; ?>
            </div>
            <div class="box-right">box-right</div>
            <footer>footer</footer>
        </div>
    </body>
</html>
